version: '3.9'
services:
  dbft_api:
    build: ${API_BUILD_DIR}#${API_BRANCH}
    # build: ../../OGrEE-API
    image: dbft/api:dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_api
    environment:
      - api_port=3551
      - db_host=${COMPOSE_PROJECT_NAME}_db
      - db_port=27017
      - db_user=$COMPOSE_PROJECT_NAME
      - db_pass=$CUSTOMER_API_PASSWORD
      - db=$COMPOSE_PROJECT_NAME
      - token_password=yourSecretPasswordGoesHere
    ports:
      - ${API_PORT}:3551
    depends_on:
      - dbft_db
    restart: on-failure:10

    #Specifying the environment variables here is the superior option compared to inserting
    #the .env file and building an image. Here you can specify all the parameters of the
    #the API 

  dbft_db:
    image: mongo:latest
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
        - DB_NAME=$COMPOSE_PROJECT_NAME
        - CUSTOMER_API_PASSWORD=$CUSTOMER_API_PASSWORD
        - ADMIN_DB=admin
        - SUPER_USER=super
        - SUPER_PASS=superpassword
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=adminpassword
        - GUARD_USER=guard
        - GUARD_PASS=adminpassword
    volumes:
        -  ./init.sh:/docker-entrypoint-initdb.d/init.sh
        -  ../createdb.js:/home/createdb.js
    #By default MongoDB will attempt to take port 27017, so just map it
    #for ease of use


  # Deploying the CLI in an orchestrated fashion does 
  # not work since containers exit when a program
  # is done executing. Instead make container 'hang'
  # to allow for on demand access. 
  # The 'tty: true' entry allows the container to hang 
  # by using the container's shell
  # The cli binary is found @ /home/cli

  # Environment notes:
  # Drawable -> You should specify a string with multiple objects separated by ':'
  # Updates -> Same thing as Drawable
  # {obj}DrawableJson -> Specify them as usual, objDrawableJson="xyz"
  dbft_cli:
    build: ${CLI_BUILD_DIR}#${CLI_BRANCH}
    image: dbft/cli:dockerfile
    profiles: ["cli"]
    container_name: ${COMPOSE_PROJECT_NAME}_cli
    tty: true
    environment:
      - APIKEY=YourAPIKEYGoesHere
      - APIURL=http://0.0.0.0:${API_PORT}
      - DrawLimit=1
      - Drawable=all
      - tenantDrawableJson=./other/drawTemplates/tenant.json
      - UnityTimeout=10ms
      - UnityURL=localhost:5500
      - Updates=all
      - User=new@yo.com
    depends_on:
      - dbft_api

  # You will have to retrieve the swagger.json file from
  # the api root dir and supply it here 
  api_docs_ui:
    image: swaggerapi/swagger-ui:latest
    container_name: api_docs_ui
    network_mode: "bridge"
    profiles: ["doc"]
    volumes:
      - ${API_DOC_DIR}/swagger.json:/home/swagger.json
    ports:
      - ${API_DOC_UI_PORT}:8080
    environment:
      SWAGGER_JSON: /home/swagger.json

  dbft_webapp:
    build: 
      context: ${APP_BUILDDIR}#${APP_BRANCH}
      args:
      - API_URL=http://${API_EXTERNALURL}:${API_PORT}
    image: dbft/webapp:dockerfile
    profiles: ["web"]
    container_name: ${COMPOSE_PROJECT_NAME}_webapp
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - dbft_api
    restart: on-failure:10
