APIKEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRyYXNoQHlvLmNvbSJ9.UNfTHCA-Cm0OBqKgXqxDs5XhrXn7IAM6hBKNlDyOTHk"
apiKeyAuthorisedMitsubishi="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjAsIkRvbWFpbiI6IkQyIiwiUm9sZSI6InVzZXIifQ.n74qdBDwTYE_mrL-hHR3IQJtk12yduEyAQ3FnTfgXdE"
APIURL="http://localhost:3001"
apiURLCAPI="https://c.api.ogree.ditrit.io"
apiURLGENERALE="https://api.ogree.ditrit.io"
apiURLVAPI="https://v.api.ogree.ditrit.io"
apiURLlOCALE="http://localhost:3001"
DrawLimit=1
Drawable=["all"]

#DrawableJsons
#Take the form objDrawableJson
DrawableJson= { tenantDrawableJson = "./other/drawTemplates/tenant.json"}
UnityURL="localhost:5500"
Updates=["all"]
User="new@new.com"
