on:
  pull_request:
    branches:
    - master
    paths:
    - API

name: CLI Unit Tests

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CLI
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.6

    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build
      run: make
    
    - name: Test
      run: go test
